### PR TITLE
Added Logitech F310 support

### PR DESCRIPTION
**Pull request by shortstheory**
This patch adds the button mapping and detection for the popular Logitech F310 USB controller. All basic functions supported.

### CODE REVIEW

**Comment by hanyazou** [comment]
Hi shortstheory,

Thank you for your contribution.
Can you remove this change bellow from your pull request so that I can merge your F310 code?

- import cv2.cv2 as cv2  # for avoidance of pylint error
+ import cv2

**Comment by shortstheory** [comment]
Hi, I just updated my fork to reflect this change.

**Comment by hanyazou** [comment]
Thanx but it contains an additional space. Please delete the space.

https://github.com/shortstheory/TelloPy/commit/88611932fd4894790843e7686c564d6777fe437a

**Comment by shortstheory** [comment]
Done, please take a look.

**Comment by hanyazou** [comment]
Done!

**Pull request merged**
