### PR TITLE
Addition for newer PS4 controllers

### PR DESCRIPTION
**Pull request by ibrokemycomputer**
A simple update to allow alternate Sony controller names. Tested with my Tello on Ubuntu 18.10 with a Dualshock 4 controller that was purchased today (after I had issues with my Steelseries Stratus XL).

### CODE REVIEW

**Comment by ibrokemycomputer** [comment]
An additional note, the "ALT" controller uses the same mapping as the default PS4 ('Wireless Controller') when connected via Bluetooth and this PR does not affect that.

**Comment by hanyazou** [comment]
I don't have that controller.
Which map JoystickPS4 or JoystickPS4ALT is proper for 'Sony Interactive Entertainment Wireless Controller'?

**Comment by ibrokemycomputer** [comment]
JoystickPS4ALT is for 'Sony Interactive Entertainment Wireless Controller'. Looking back at what I submitted I see I was too tired to be coding when I submitted the PR yesterday. Oops! I removed the duplicate string/cleaned up the code.

**Comment by hanyazou** [comment]
Could you please use 'elif' instead of 'if'?

**Comment by ibrokemycomputer** [comment]
Updated!

**Comment by hanyazou** [comment]
done! thank you.

**Pull request merged**
